data:
  transactions: "../../dataset/credit_card_transactions-ibm_v2.csv"
  max_rows: null
  train_fraction: 0.7
  val_fraction: 0.15

sampling:
  method: "uniform" # Pilihan: uniform, topology, importance
  undersampling_ratio: 0.02 # Dari 0.1 menjadi 0.02 (sesuai paper 2% undersampling rate)

model:
  hidden_channels: 128 # Dari 256 menjadi 128
  out_channels: 1
  num_layers: 2
  aggr: "mean"

training:
  batch_size: 1024 # Diperbesar agar stabil
  epochs: 10 # Dari 5 menjadi 10 (berdasarkan file Experimental Pipeline.ipynb di referensi)
  learning_rate: 0.001
  num_neighbors: [15, 10] # Standard GraphSAGE

output:
  model_dir: "../../model/exp16"
  result_dir: "../../result/exp16"
