"""Build a deterministic, credential-free EXP13 Kaggle script bundle.

The private API key stays in ``kaggle.json``. Only the public Kaggle username is
written to kernel metadata. Every run gets its own slug, so a later strategy or
seed cannot overwrite an earlier result.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
from io import BytesIO
import json
from pathlib import Path
import re
import sys
import zipfile

from exp13.engine import ENGINE_ROOT, ROOT, engine_files, engine_manifest, expose_engine


KAGGLE_DIR = ROOT / "kaggle"
ACCELERATOR = "NvidiaTeslaT4"
DATASET_SOURCE = "ealtman2019/credit-card-transactions"


def load_credential(path: Path | None = None) -> tuple[str, str]:
    """Validate the legacy Kaggle credential without ever logging its token."""
    credential_path = (path or ROOT / "kaggle.json").resolve()
    try:
        raw = json.loads(credential_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise FileNotFoundError(
            f"Credential tidak ditemukan: {credential_path}. Simpan sebagai kaggle.json lokal."
        ) from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"Credential bukan JSON valid: {credential_path}") from exc
    username = str(raw.get("username", "")).strip()
    key = str(raw.get("key", "")).strip()
    if not username or not key:
        raise ValueError("kaggle.json harus memuat username dan key yang tidak kosong")
    if not re.fullmatch(r"[A-Za-z0-9_-]+", username):
        raise ValueError("Username Kaggle mengandung karakter yang tidak aman untuk metadata")
    return username.lower(), key


def merged_config(strategy: str, seed: int) -> dict:
    expose_engine()
    from exp12.config import load_config, validate_config

    cfg = load_config(ROOT / "config.yaml")
    cfg["experiment"].update(
        name=f"exp13_{strategy}_s{seed}",
        device="cuda",
        strategies=[strategy],
        seeds=[seed],
        on_existing="error",
        overwrite=False,
    )
    # These are overridden by the generated launcher too; portable values keep
    # the embedded configuration free of developer-machine absolute paths.
    cfg["data"]["transactions"] = "/kaggle/input/credit-card-transactions/credit_card_transactions-ibm_v2.csv"
    cfg["paths"]["model_dir"] = f"/kaggle/working/model/exp13/{strategy}_s{seed}"
    cfg["paths"]["result_dir"] = f"/kaggle/working/result/exp13/{strategy}_s{seed}"
    validate_config(cfg)
    return cfg


def payload(strategy: str, seed: int) -> tuple[str, str]:
    buffer = BytesIO()
    configuration = merged_config(strategy, seed)
    manifest = {
        "experiment": "EXP13",
        "engine": "EXP12",
        "strategy": strategy,
        "seed": seed,
        "engine_sha256": engine_manifest(),
    }
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in engine_files():
            info = zipfile.ZipInfo(path.relative_to(ENGINE_ROOT).as_posix())
            info.date_time = (2026, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, path.read_bytes())
        for name, content in (
            ("config.exp13.json", json.dumps(configuration, indent=2, sort_keys=True)),
            ("EXP13_SOURCE_MANIFEST.json", json.dumps(manifest, indent=2, sort_keys=True)),
        ):
            info = zipfile.ZipInfo(name)
            info.date_time = (2026, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, content.encode("utf-8"))
    binary = buffer.getvalue()
    return base64.b64encode(binary).decode("ascii"), hashlib.sha256(binary).hexdigest()


def kernel_source(strategy: str, seed: int) -> tuple[str, str]:
    encoded, digest = payload(strategy, seed)
    run_tag = f"{strategy}_s{seed}"
    arguments = ["--strategy", strategy, "--seed", str(seed), "--device", "cuda"]
    script = f'''# Generated by EXP13 build_kaggle_kernel.py. Do not edit manually.
import base64
import importlib.util
from io import BytesIO
from pathlib import Path
import shutil
import subprocess
import sys
import zipfile

REQUIRED = {{"duckdb": "duckdb>=1.1,<2", "torch_geometric": "torch-geometric>=2.5,<3", "yaml": "pyyaml>=6,<7"}}
missing = [package for module, package in REQUIRED.items() if importlib.util.find_spec(module) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "--no-input", *missing])

import torch
if not torch.cuda.is_available():
    raise RuntimeError("EXP13 mewajibkan CUDA GPU T4; runtime Kaggle ini berjalan tanpa GPU.")
gpu_name = torch.cuda.get_device_name(0)
if "T4" not in gpu_name.upper():
    raise RuntimeError(f"EXP13 dikunci ke NVIDIA T4, tetapi accelerator aktual adalah: {{gpu_name}}")
torch.empty(1, device="cuda").add_(1).cpu()
print(f"EXP13 accelerator verified: {{gpu_name}}")

bundle = Path("/kaggle/working/_exp13_bundle_{run_tag}")
bundle.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(BytesIO(base64.b64decode("{encoded}"))) as archive:
    archive.extractall(bundle)
sys.path.insert(0, str(bundle))

exact = sorted(Path("/kaggle/input").rglob("credit_card_transactions-ibm_v2.csv"))
if not exact:
    exact = sorted(path for path in Path("/kaggle/input").rglob("*.csv") if "credit" in path.name.lower())
if len(exact) != 1:
    raise FileNotFoundError(f"Diharapkan tepat satu CSV transaksi IBM v2; ditemukan: {{exact}}")

from exp12.cli import main
model_dir = Path("/kaggle/working/model/exp13/{run_tag}")
result_dir = Path("/kaggle/working/result/exp13/{run_tag}")
args = [
    "--config", str(bundle / "config.exp13.json"),
    "--data", str(exact[0]),
    "--model-dir", str(model_dir),
    "--result-dir", str(result_dir),
    *{json.dumps(arguments)},
]
code = int(main(args) or 0)
if code != 0:
    raise SystemExit(code)

# The ~2 GiB preprocessing cache is reproducible and not useful as a Kaggle
# output artifact. Keep checkpoints, metrics, histories, and source manifest.
shutil.rmtree(model_dir / "cache", ignore_errors=True)
shutil.copy2(bundle / "EXP13_SOURCE_MANIFEST.json", result_dir / "EXP13_SOURCE_MANIFEST.json")
print("EXP13 completed; transient preprocessing cache removed from kernel output.")
raise SystemExit(0)
'''
    return script, digest


def metadata(username: str, strategy: str, seed: int) -> dict:
    slug = f"graphsage-fraud-exp13-{strategy}-s{seed}"
    return {
        "id": f"{username}/{slug}",
        "title": f"GraphSAGE Fraud EXP13 {strategy.title()} S{seed}",
        "code_file": "kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "machine_shape": ACCELERATOR,
        "dataset_sources": [DATASET_SOURCE],
        "competition_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }


def build(strategy: str, seed: int, credential_path: Path | None = None) -> dict:
    if strategy not in {"uniform", "topology", "importance"}:
        raise ValueError(f"Strategi tidak dikenal: {strategy}")
    if not 0 <= seed < 2**32:
        raise ValueError("Seed harus berada dalam [0, 2**32)")
    username, secret = load_credential(credential_path)
    source, payload_sha = kernel_source(strategy, seed)
    kernel_metadata = metadata(username, strategy, seed)
    metadata_text = json.dumps(kernel_metadata, indent=2) + "\n"
    if secret in source or secret in metadata_text:
        raise RuntimeError("Build dibatalkan: token credential terdeteksi pada artefak Kaggle")
    KAGGLE_DIR.mkdir(parents=True, exist_ok=True)
    (KAGGLE_DIR / "kernel.py").write_text(source, encoding="utf-8", newline="\n")
    (KAGGLE_DIR / "kernel-metadata.json").write_text(metadata_text, encoding="utf-8", newline="\n")
    return {
        "kernel": str(KAGGLE_DIR / "kernel.py"),
        "metadata": str(KAGGLE_DIR / "kernel-metadata.json"),
        "kernel_ref": kernel_metadata["id"],
        "accelerator": ACCELERATOR,
        "payload_sha256": payload_sha,
        "credential_embedded": False,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build a secure EXP13 Kaggle T4 kernel")
    parser.add_argument("--strategy", choices=["uniform", "topology", "importance"], default="uniform")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--credential", type=Path, default=ROOT / "kaggle.json")
    args = parser.parse_args(argv)
    result = build(args.strategy, args.seed, args.credential)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
