data:
  transactions: "../../dataset/credit_card_transactions-ibm_v2.csv"
  max_rows: null
  train_fraction: 0.7
  val_fraction: 0.15

sampling:
  method: "uniform" # Pilihan: uniform, topology, importance
  undersampling_ratio: 0.3 # Moderate ratio untuk menjaga struktur graf

model:
  hidden_channels: 256
  out_channels: 1
  num_layers: 3
  aggr: "max"

training:
  batch_size: 1024 # Diperbesar agar stabil
  epochs: 10 # Dari 5 menjadi 10 (berdasarkan file Experimental Pipeline.ipynb di referensi)
  learning_rate: 0.001
  num_neighbors: [15, 10] # Standard GraphSAGE

output:
  model_dir: "../../model/exp19"
  result_dir: "../../result/exp19"
