"""Build the single-file script required by ``kaggle kernels push``.

The editable source remains modular under ``exp12/``.  This builder embeds that
package and the Kaggle preset in a deterministic zip payload inside kernel.py.
"""
from __future__ import annotations

import argparse
import base64
from io import BytesIO
import json
from pathlib import Path
import zipfile


ROOT = Path(__file__).resolve().parent


def payload():
    buffer = BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted((ROOT / "exp12").rglob("*.py")):
            info = zipfile.ZipInfo(path.relative_to(ROOT).as_posix())
            info.date_time = (2026, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, path.read_bytes())
        for name in ("config.yaml", "config.kaggle.yaml"):
            info = zipfile.ZipInfo(name)
            info.date_time = (2026, 1, 1, 0, 0, 0)
            info.compress_type = zipfile.ZIP_DEFLATED
            archive.writestr(info, (ROOT / name).read_bytes())
    return base64.b64encode(buffer.getvalue()).decode("ascii")


def build(strategy, seed):
    target = ROOT / "kaggle" / "kernel.py"
    target.parent.mkdir(parents=True, exist_ok=True)
    arguments = ["--strategy", strategy, "--seed", str(seed)]
    script = f'''# Generated by build_kaggle_kernel.py; edit modular sources, not this file.
import base64
import importlib.util
from io import BytesIO
from pathlib import Path
import subprocess
import sys
import zipfile

REQUIRED = {{"duckdb": "duckdb>=1.1,<2", "torch_geometric": "torch-geometric>=2.5,<3", "yaml": "pyyaml>=6,<7"}}
missing = [package for module, package in REQUIRED.items() if importlib.util.find_spec(module) is None]
if missing:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "--quiet", "--no-input", *missing])

bundle = Path("/kaggle/working/_exp12_bundle")
bundle.mkdir(parents=True, exist_ok=True)
with zipfile.ZipFile(BytesIO(base64.b64decode("{payload()}"))) as archive:
    archive.extractall(bundle)
sys.path.insert(0, str(bundle))

exact = list(Path("/kaggle/input").rglob("credit_card_transactions-ibm_v2.csv"))
if not exact:
    exact = [path for path in Path("/kaggle/input").rglob("*.csv") if "credit" in path.name.lower()]
if len(exact) != 1:
    raise FileNotFoundError(f"Diharapkan tepat satu CSV transaksi IBM; ditemukan: {{exact}}")

from exp12.cli import main
args = [
    "--config", str(bundle / "config.kaggle.yaml"),
    "--data", str(exact[0]),
    "--model-dir", "/kaggle/working/model/exp12_kaggle",
    "--result-dir", "/kaggle/working/result/exp12_kaggle",
    *{json.dumps(arguments)},
]
raise SystemExit(main(args))
'''
    target.write_text(script, encoding="utf-8", newline="\n")
    return target


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--strategy", choices=["uniform", "topology", "importance"], default="uniform")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    print(build(args.strategy, args.seed))


if __name__ == "__main__":
    main()
